import SwiftUI

struct ContentView: View {
    @EnvironmentObject var store: GameStore
    var body: some View { NavigationStack { HomeView() }.tint(.blue) }
}
struct HomeView: View {
    @EnvironmentObject var store: GameStore
    var body: some View { ZStack { SkyBackground(); VStack(spacing: 0) { HUD(points: store.points); Spacer(); Text("AI 单词闯关").font(.system(size: 48, weight: .black, design: .rounded)).foregroundStyle(.white).shadow(color: .blue.opacity(0.45), radius: 3); Text("WORD QUEST").font(.caption.bold()).foregroundStyle(.white.opacity(0.9)); Spacer(); NavigationLink { LevelView() } label: { BlockButton(title: "闯关挑战", icon: "flag.fill", color: .green) }; HStack(spacing: 14) { NavigationLink { WrongView() } label: { BlockButton(title: "错题集", icon: "exclamationmark.triangle.fill", color: .orange) }; NavigationLink { RewardView() } label: { BlockButton(title: "奖励", icon: "gift.fill", color: .yellow) } }; Spacer(); Hotbar() }.padding(24) }.navigationBarHidden(true) }
}
struct LevelView: View {
    @EnvironmentObject var store: GameStore
    var body: some View { ZStack { SkyBackground(); ScrollView { VStack(spacing: 18) { HUD(points: store.points); Text("选择关卡").font(.title.bold()).foregroundStyle(.white); ForEach(Array(store.levels.enumerated()), id: \.offset) { i, _ in let n = i + 1; NavigationLink { QuizView(level: n) } label: { LevelBlock(number: n, unlocked: n <= store.unlocked) }.disabled(n > store.unlocked) } } .padding(24) } }.navigationBarTitleDisplayMode(.inline) }
}
struct QuizView: View {
    @EnvironmentObject var store: GameStore; let level: Int
    @State private var items: [Word] = []; @State private var index = 0; @State private var correct = 0; @State private var options: [String] = []; @State private var locked = false; @State private var done = false
    var body: some View { Group { if done { VStack(spacing: 20) { Text("第 \(level) 关完成").font(.largeTitle.bold()); Text("答对 \(correct) / 20"); Text("获得积分：\(correct == 20 ? 50 : (20-correct <= 2 ? 30 : (20-correct <= 5 ? 10 : 0)))"); NavigationLink("返回关卡", destination: LevelView()) } } else if items.isEmpty { ProgressView() } else { let w = items[index]; VStack(spacing: 24) { ProgressView(value: Double(index), total: 20); Text(w.english).font(.system(size: 52, weight: .bold)).onTapGesture { store.click(); store.speak(w.english) }; Button { store.click(); store.speak(w.english) } label: { Label("播放标准发音", systemImage: "speaker.wave.2.fill") }; ForEach(options, id: \.self) { answer in Button(answer) { submit(answer, w) }.buttonStyle(.borderedProminent).disabled(locked) } }.padding() } }.navigationTitle("第 \(level) 关").onAppear { items = store.levels[level-1].shuffled(); nextOptions() } }
    func nextOptions() { guard index < items.count else { return }; let answer = items[index].chinese; options = ([answer] + store.words.filter { $0.chinese != answer }.shuffled().prefix(3)).shuffled() }
    func submit(_ answer: String, _ word: Word) { locked = true; store.click(); if answer == word.chinese { correct += 1 } else { store.wrong.insert(word.english); store.save() }; DispatchQueue.main.asyncAfter(deadline: .now()+0.35) { if index == 19 { store.finish(level: level, correct: correct); done = true } else { index += 1; locked = false; nextOptions() } } }
}
struct WrongView: View { @EnvironmentObject var store: GameStore; var body: some View { List(store.words.filter { store.wrong.contains($0.english) }) { w in Button { store.click(); store.speak(w.english) } label: { VStack(alignment: .leading) { Text(w.english).font(.headline); Text(w.chinese).foregroundStyle(.secondary) } } }.navigationTitle("错题集") } }
struct RewardView: View { @EnvironmentObject var store: GameStore; var body: some View { List { Text("500 积分：可以玩电脑一次"); Text("2000 积分：可以去游乐场一次"); Text("当前积分：\(store.points)") }.navigationTitle("奖励机制") } }

struct SkyBackground: View { var body: some View { LinearGradient(colors: [.cyan.opacity(0.8), .blue.opacity(0.35), .green.opacity(0.65)], startPoint: .top, endPoint: .bottom).ignoresSafeArea().overlay(alignment: .bottom) { Rectangle().fill(.green.opacity(0.65)).frame(height: 90).overlay { HStack(spacing: 0) { ForEach(0..<18, id: \.self) { _ in Rectangle().fill(.brown.opacity(0.45)).frame(width: 38, height: 12) } } .offset(y: 18) } } } }
struct HUD: View { let points: Int; var body: some View { HStack { Text("✚ AI").font(.headline.bold()).foregroundStyle(.white); Spacer(); Label("\(points)", systemImage: "circle.fill").font(.headline.bold()).foregroundStyle(.yellow); Image(systemName: "gearshape.fill").foregroundStyle(.white) }.padding(12).background(.black.opacity(0.28), in: Rectangle()).overlay(Rectangle().stroke(.white.opacity(0.25), lineWidth: 1)) } }
struct BlockButton: View { let title: String; let icon: String; let color: Color; var body: some View { Label(title, systemImage: icon).font(.title3.bold()).frame(maxWidth: .infinity).padding(.vertical, 18).background(color.gradient, in: Rectangle()).overlay(Rectangle().stroke(.black.opacity(0.35), lineWidth: 4)).shadow(color: .black.opacity(0.3), radius: 0, x: 0, y: 7).foregroundStyle(.white) } }
struct LevelBlock: View { let number: Int; let unlocked: Bool; var body: some View { HStack { Image(systemName: unlocked ? "flag.fill" : "lock.fill").font(.title2); Text("第 \(number) 关").font(.title3.bold()); Spacer(); Text(unlocked ? "进入" : "未解锁").font(.subheadline.bold()) }.foregroundStyle(unlocked ? .white : .white.opacity(0.55)).padding(18).frame(maxWidth: .infinity).background((unlocked ? Color.green : Color.gray).gradient, in: Rectangle()).overlay(Rectangle().stroke(.black.opacity(0.4), lineWidth: 4)).shadow(color: .black.opacity(0.3), radius: 0, x: 0, y: 6) } }
struct Hotbar: View { var body: some View { HStack(spacing: 3) { ForEach(0..<7, id: \.self) { i in ZStack { Rectangle().fill(.black.opacity(0.38)); Rectangle().stroke(.white.opacity(i == 0 ? 0.9 : 0.3), lineWidth: 2); if i == 0 { Image(systemName: "book.fill").foregroundStyle(.white) } } .frame(width: 42, height: 42) } }.padding(5).background(.black.opacity(0.35), in: Rectangle()) } }
